colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "joey-kyber-Mg2iKRWpiCk-unsplash.jpg"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "6"
showMoreLink = false
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showAuthorBottom = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = ""
showWordCount = true
showZenMode = false
showRelatedContent = true
relatedContentLimit = 6
heroStyle = "background"
showComments = true

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
heroStyle = "background"

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = true

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
heroStyle = "background"

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]
# Add your verification codes here after registering your site
# google = ""  # Google Search Console verification code
# bing = ""    # Bing Webmaster Tools verification code
# yandex = ""  # Yandex Webmaster verification code

[rssnext]
